### ISSUE TITLE
ioc_module#registerInContainer can not be run as "standalone"

### ISSUE THREAD

**Issue by stheuer** [essential-projects/validation#2]
#### Describe your issue
ioc_module#registerInContainer can not be run as "standalone"

#### How can others reproduce the issue?
create a npm project wit package.json
```
{
  "name": "test-validation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@essential-projects/validation": "1.0.0-rc4",
    "addict-ioc": "2.3.4",
    "@essential-projects/bootstrapper": "1.0.0-rc4",
    "@essential-projects/bootstrapper_node": "1.0.0-rc4"
  }
}
```

and index.js

```
const InvocationContainer = require('addict-ioc').InvocationContainer

const iocModuleNames = [
  '@essential-projects/bootstrapper',
  '@essential-projects/bootstrapper_node',
  '@essential-projects/validation'
];

const iocModules = iocModuleNames.map((moduleName) => {
  return require(`${moduleName}/ioc_module`);
});

async function start() {
  const container = new InvocationContainer({
    defaults: {
      conventionCalls: ['initialize'],
    },
  });

  for (const iocModule of iocModules) {
    iocModule.registerInContainer(container);
  }

  container.validateDependencies();

  try {
    const bootstrapper = await container.resolveAsync('AppBootstrapper');
    await bootstrapper.start();

    logger.info('Bootstrapper started successfully.');
  } catch(error) {
    logger.error('Bootstrapper failed to start.', error);
  }
}
start();
```

running index produxes errors
```
 node index.js
.................
[ 'registration for key "NamingConventionService" is missing',
  'registration for key "NamingConventionService" is missing' ]
.................
(node:25184) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: validation failed
(node:25184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
#### Possible solution
make @essential-projects/validate depend on @essential-projects/core  if it does not break the architecture

#### What's your setup

- OS Windows
- Node v8.9.0
- NPM 5.5.1

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
We have everything loosely coupled, so that the implementations of the packages can be swapped out easily.

validation requires, that a NamingConventionService is registered to the ioc-container. But what if you want to use your own NamingConventionService, and not the one from `@essential-projects/core`?

Because we don't want to couple packages in a hard way, it's the developers responsibility to make sure that everything necessary is registered to the ioc-container. In your example you'd make your example-application depend on `@essential-projects/core`, and add it to your `iocModuleNames`.

Does this solve your problem?

**Comment by stheuer** [comment]
works as designed
